[unstable]
# recompile `core` and other standard library crates on demand
build-std = ["core", "compiler_builtins"]
# enable build in memory functions
build-std-features = ["compiler-builtins-mem"]

[build]
# use build target in this directory
target = "x86_64-unknown-none.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
