#!/bin/bash
#
# Copyright 2013 Victor Penso
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo "
  '\\e[<NUM>m' or '\\e[<NUM>;<NUM>;...;<NUM>m'
  
  Text modifiers
    0 (off) 1 (bold) 4 (underscore) 5 (blink) 7 (reverse) 8 (concealed)  
  8 colors (Bold)
   [30m 30 [31m 31 [32m 32 [33m 33 [34m 34 [35m 35 [36m 36 [37m 37 [0m
  [1m [30m 30 [31m 31 [32m 32 [33m 33 [34m 34 [35m 35 [36m 36 [37m 37 [0m

  '\\e[38;5;<NUM>m' foreground and '\e[48;5;<N>m' background 256 colors 
  '\e[38;2;<r>;<g>;<b>m' foreground and '\\e[48;2;<r>;<g>;<b>m' background 24bit colors

  256 colors
"

echo -n "[38;5;16m    "

steps=0
for i in {16..99}
do 
  echo -n "[48;5;${i}m ${i}  "
  if [ "$steps" == "5" ] 
  then
    steps=0
    echo 
    echo -n "[0m    [30m"
  else
    steps=$[steps+1]
  fi
done 

steps=0
for i in {100..255}
do 
  echo -n "[48;5;${i}m ${i} "
  if [ "$steps" == "5" ] 
  then
    steps=0
    echo 
    echo -n "[0m    [30m"
  else
    steps=$[steps+1]
  fi
done 

echo "[0m"

exit 0
