#!/bin/bash
#
# Copyright 2013 Victor Penso
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

sudo apt-get update

# Install basic software use on a workstation
sudo apt-get -y install vim zsh tmux git-core chef ruby-full python-pygments curl psmisc htop ack-grep sysstat procps iptraf tcpdump nmap clustershell sshuttle ipmitool freeipmi-tools mpd mpc

