#!/bin/bash

echo "Action key is Ctrl-a
Hold Shift to select text with mouse

    Ctrl-a ?       │ show key binding
    Ctrl-a -       │ new horizontal pane
    Ctrl-a |       │ new vertical pane  
    Alt ←/↑/→/↓    │ move between panes
    Ctrl-a ←/↑/→/↓ │ resize panes
    Ctrl-a x       │ close pane
    Ctrl-a c       │ new window
    Ctrl-a ,       │ rename window
    Ctrl-a n/p     │ next/previous window
    Ctrl-a w       │ list windows
    Ctrl-a d       │ detach from session (run tmux attach)
    Ctrl-a a       │ send prefix key to program in pane 
    
Shell key-binding

    Ctrl-r         │ search command history 
    Ctrl-p         │ last command
    Ctrl-z         │ suspend process to background 
    Ctrl-c         │ break current execution
    Ctrl-t         │ transpose current character
    Ctrl-a         │ cursor to beginning of line
    Ctrl-e         │ cursor to end of line
    Ctrl-l         │ clear screen
    Ctrl-u         │ discard line
    Ctrl-w         │ remove last word 
    Ctrl-k         │ remove until end of line 
    Ctrl-b         │ cursor one word left 
    Ctrl-f         │ cursor one word right 

Simultaneous keyboard input on all panes:

    Ctrl-a :setw synchronize-panes [on|off]
"
