#!/bin/bash

config=$HOME/.tmux.conf

if [ -e $config ]
then
  echo "Tmux configuration $config already exits!"
  exit 0
fi

cat > $config <<EOF
set -g default-terminal "screen-256color"

# uncomment for GUI support
set -g mode-mouse on
setw -g mouse-select-window on
setw -g mouse-select-pane on
setw -g monitor-activity on
set -g visual-activity on
setw -g automatic-rename

set-option -g prefix C-a
unbind C-b
bind-key C-a last-window

bind a send-prefix

# force reload of config file
unbind r
bind r source-file ~/.tmux.conf

unbind %
bind | split-window -h
bind - split-window -v 

# pane switching with Alt arrows 
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# keybindings to make resizing easier
bind -r Left resize-pane -L
bind -r Right resize-pane -D
bind -r Up resize-pane -U
bind -r Down resize-pane -R

# status line
set -g status-fg colour244
set -g status-bg default
set -g pane-border-fg colour240
set -g pane-active-border-fg colour33
set -g message-fg colour240
set -g message-bg default
set -g status-left '#[fg=colour235,bold] #S '
set -g status-right 'VM #(virsh list | grep running | wc -l) │ LD#(uptime | cut -d, -f 4- | cut -d: -f2) '
set -g window-status-format "#[fg=colour250] #I:#W "
set -g window-status-current-format "#[fg=colour33,bold] #W "

##
## Custom configuration...
##
EOF

echo "Tmux configuration written to $config."
