#!/bin/bash

config=$HOME/.tmux.conf

if [ -e $config ]
then
  echo "Tmux configuration $config already exits!"
  exit 0
fi

cat > $config <<EOF
set -g default-terminal "screen-256color"

# uncomment for GUI support
set -g mode-mouse on
setw -g mouse-select-window on
setw -g mouse-select-pane on
setw -g monitor-activity on
set -g visual-activity on
setw -g automatic-rename

set-option -g prefix C-a
unbind C-b
bind-key C-a last-window

bind a send-prefix

# force reload of config file
unbind r
bind r source-file ~/.tmux.conf

unbind %
bind | split-window -h
bind - split-window -v 

# pane switching with Alt arrows 
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# keybindings to make resizing easier
bind -r Left resize-pane -L
bind -r Right resize-pane -D
bind -r Up resize-pane -U
bind -r Down resize-pane -R

# status line
set -g status-left-length 52
set -g status-right-length 451
set -g status-fg colour244
set -g status-bg colour232
set -g window-status-activity-attr bold
set -g pane-border-fg colour245
set -g pane-active-border-fg colour250
set -g message-fg colour16
set -g message-bg colour221
set -g message-attr bold
set -g status-left '#[fg=colour234,bg=colour240,bold] ❐ #S #[fg=colour240,bg=colour233,bold]⮀'
set -g status-right "#[fg=colour234,bg=colour232]⮂#[fg=colour239,bg=colour234] VM #(virsh list | grep running | wc -l) ⮃ MF #(free | grep Mem | awk '{print $4/$2 * 100.0}'| cut -c -5)% ⮃ LD#(uptime | cut -d, -f 4- | cut -d: -f2)"
set -g window-status-format "#[fg=colour252,bg=colour232] #I #W "
set -g window-status-current-format "#[fg=colour252,bg=colour234,noreverse,bold] #I #W #[fg=colour240,bg=colour232,nobold]"

##
## Custom configuration...
##
EOF

echo "Tmux configuration written to $config."
