#!/bin/zsh
#
## Copyright 2012 Victor Penso
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##

mkdir ~/.zsh 2>-

# Antigen package management for zsh plug-ins
ANTIGEN=https://raw.github.com/zsh-users/antigen/master/antigen.zsh
if [ ! -e ~/.zsh/antigen.zsh ] ; then
  curl --silent $ANTIGEN > ~/.zsh/antigen.zsh
  echo "ZSH anitgen installed to ~/.zsh/"
fi


##
## Zsh configuration file
##
if [ -e $HOME/.zshrc ] ; then
echo "Zsh configuration ~/.zshrc exists!"
  exit 0
fi

cat > $HOME/.zshrc <<'EOF'
export ADOTDIR=~/.zsh
source ~/.zsh/antigen.zsh

antigen-bundle git
antigen-bundle oscarschneider/knife-completion

antigen-bundle zsh-users/zsh-syntax-highlighting

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES+=(
  reserved-word          'fg=27,bold'
  command                'fg=27,bold'
  hashed-command         'fg=27,bold'
  alias                  'fg=39,bold'
  builtin                'fg=27,bold'
  function               'fg=39,bold'
  path                   'fg=246'
  single-quoted-argument 'fg=220,bold'
  double-quoted-argument 'fg=220,bold'
)

antigen-bundle olivierverdier/zsh-git-prompt

__GIT_PROMPT_DIR=~/.zsh/repos/https-COLON--SLASH--SLASH-github.com-SLASH-olivierverdier-SLASH-zsh-git-prompt.git/

export __GIT_PROMPT_DIR

ZSH_THEME_GIT_PROMPT_PREFIX=""
ZSH_THEME_GIT_PROMPT_SUFFIX=" "
ZSH_THEME_GIT_PROMPT_SEPARATOR=""
ZSH_THEME_GIT_PROMPT_CLEAN=""
ZSH_THEME_GIT_PROMPT_STAGED="%F{166}●"
ZSH_THEME_GIT_PROMPT_CONFLICTS="%F{166}✖"
ZSH_THEME_GIT_PROMPT_CHANGED="%F{26}✚"
ZSH_THEME_GIT_PROMPT_BRANCH="%F{243}"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%F{166}…"

antigen-apply

PROMPT='$(git_super_status)%F{253}»%f '
RPROMPT='%F{234}%n%F{253}:%F{243}%~%k%f'

autoload -U colors && colors
if [ -e $HOME/.dir_colors/rainbow ] ; then
  eval $(dircolors $HOME/.dir_colors/rainbow)
fi

if [ -f $HOME/.zsh_config_hook ]
then
  source $HOME/.zsh_config_hook
fi

export TERM="screen-256color"
EOF
echo "Configuration written to ~/.zshrc"

# make zsh default shell
shell=$(getent passwd $USER | cut -d':' -f 7)
if [ ! "$shell" = "/bin/zsh" ] ; then
  chsh -s /bin/zsh
  echo "Re-login to your user account."
fi
