# micro controller used by the Micro:Bit V2
[default.general]
chip = "nrf52833_xxAA" 

# halt the chip after we flashed it so our program does not instantly jump to the loop
[default.reset]
halt_afterwards = true

# disable text debugging
[default.rtt]
enabled = false

# enable the GDB debugger
[default.gdb]
enabled = true
