export HISTSIZE=100000                       # set history size
export SAVEHIST=$HISTSIZE                    # save history after logout
export HISTCONTROL=ignoreboth                # [BASH] ignore entries with leading white space and dupes.

# simple shell prompt
export PS1="\n\t \e[32m\u\e[0m@\e[34m\h\e[0m:\e[31m\w\e[0m -- \#:\j \n\e[37;1m>>>\e[0m "	
# \e[<num>m     ASCI escape ANSI code
# \u            user name
# \h            hostname
# \#            current command number
# \j            background jobs
