export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.zsh_history
setopt append_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

setopt INTERACTIVE_COMMENTS

export PROMPT=$'\n%T \e[32m%n\e[0m@\e[34m%m\e[0m:\e[31m%~\e[0m -- %!:%j \n>>> '

# add additional configuration to this directory
mkdir ~/.zshrc.d 2>/dev/null
# if the directory is not empty
if ! [ -z "$(ls -A ~/.zshrc.d)" ]
then
	for file in `\ls ~/.zshrc.d/*`
	do 
  		source $file
	done
fi

## Line Editor - Vi Mode Configuration ##

# esc to switch to normal mode, i/a for insert/append
bindkey -v

# set delay after ESC to 0.1 second
export KEYTIMEOUT=1    

# preserver a couple of keys in insert mode
# (list widgets with `zle -la`, list keys with `bindkey`)

# make delete and backspace work
bindkey '^[[3~' delete-char
bindkey "^?" backward-delete-char
# ctrl-a/ctrl-e move cursor to beginning/end of the line
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
# ctrl-r starts searching history backward
bindkey '^r' history-incremental-search-backward

# updates editor information when the keymap changes.
function zle-keymap-select() {
  zle reset-prompt
  zle -R
}
zle -N zle-keymap-select

# represents the Vi mode indication  
function vi_mode_prompt_info() {
  echo "${${KEYMAP/vicmd/ NORMAL}/(main|viins)/ INSERT}"
}

# define right prompt, regardless of whether the theme defined it
RPS1='$(vi_mode_prompt_info)'
RPS2=$RPS1
